language: node_js

node_js:
  - '6'

sudo: required

services:
  - docker

matrix:
  include:
  - env:
    - BUILD_TASK=test
    - TAG=3.0.0
  - env:
    - BUILD_TASK=test
    - TAG=3.0.0-contrib
  - env:
    - BUILD_TASK=test
    - TAG=3.1.0
  - env:
    - BUILD_TASK=test
    - TAG=3.1.0-contrib
  - env:
    - BUILD_TASK=test
    - TAG=3.2.0
  - env:
    - BUILD_TASK=test
    - TAG=3.2.0-contrib
  - env:
    - BUILD_TASK=test
    - TAG=3.3.0
  - env:
    - BUILD_TASK=test
    - TAG=3.3.0-contrib
  - env:
    - BUILD_TASK=test
    - TAG=3.4.0
  - env:
    - BUILD_TASK=cover
    - TAG=3.4.0-contrib
  - env:
    - BUILD_TASK=test
    - TAG=3.4.1
  - env:
    - BUILD_TASK=test
    - TAG=3.4.1-contrib

install: travis_wait 30 docker pull justadudewhohacks/opencv4nodejs-ci_$TAG

script: ./ci/$BUILD_TASK/$build.sh

after_success:
  - if [ $BUILD_TASK = 'cover' ]; then
    cd ./ci/cover;
    npm install;
    npm run codecov -- -t $CODECOV_TOKEN;
    fi