name: opencv-nodejs
description: opencv4nodejs is a npm package with Node.js bindings to OpenCV
author: justadudewhohacks
author_email: muehler.v@gmail.com
baseurl: https://justadudewhohacks.github.io/opencv4nodejs
url: https://justadudewhohacks.github.io/opencv4nodejs
github_username: justadudewhohacks

# Conversion
markdown:    kramdown
highlighter: rouge

# Markdown Processors
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap